# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "my-terraform-remote-state-file-bucke-for-all-team-members-2022"
    encrypt = true
    key     = "./terraform.tfstate"
    region  = "us-east-1"
  }
}
