name: Terragrunt push AWS

on: push

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v1
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: Setup Terragrunt
      uses: eLco/setup-terragrunt@v1

    - name: Terragrunt apply all
      env:
        AWS_ACCESS_KEY_ID: ""
        AWS_SECRET_ACCESS_KEY: ""
      run: terragrunt apply-all --terragrunt-non-interactive
